/**
 * Node Palette Configuration
 * Defines all available nodes for the workflow builder
 */

import type { NodePaletteItem } from './workflow-types';

export const NODE_PALETTE: NodePaletteItem[] = [
  // ========== SOURCE NODES ==========
  {
    type: 'rss_source',
    category: 'source',
    label: 'RSS Feed',
    description: 'Fetch items from an RSS or Atom feed',
    icon: '📰',
    defaultData: {
      label: 'RSS Feed',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'http_json_source',
    category: 'source',
    label: 'HTTP JSON API',
    description: 'Fetch data from a JSON API endpoint',
    icon: '🔌',
    defaultData: {
      label: 'HTTP JSON',
      category: 'source',
      configured: false,
      method: 'GET',
      maxItems: 10,
    },
  },
  {
    type: 'web_scraper_source',
    category: 'source',
    label: 'Web Scraper',
    description: 'Extract structured data from web pages',
    icon: '🕷️',
    defaultData: {
      label: 'Web Scraper',
      category: 'source',
      configured: false,
      extractMode: 'single',
      maxItems: 1,
    },
  },
  {
    type: 'user_source',
    category: 'source',
    label: 'User Source',
    description: 'Use a saved user-defined source',
    icon: '💾',
    defaultData: {
      label: 'User Source',
      category: 'source',
      configured: false,
    },
  },
  {
    type: 'arxiv_source',
    category: 'source',
    label: 'arXiv Papers',
    description: 'Search and fetch papers from arXiv',
    icon: '📚',
    defaultData: {
      label: 'arXiv',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'hackernews_source',
    category: 'source',
    label: 'Hacker News',
    description: 'Fetch stories from Hacker News',
    icon: '🟠',
    defaultData: {
      label: 'Hacker News',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'reddit_source',
    category: 'source',
    label: 'Reddit',
    description: 'Fetch posts from subreddits',
    icon: '🤖',
    defaultData: {
      label: 'Reddit',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'github_source',
    category: 'source',
    label: 'GitHub',
    description: 'Trending repos and issues',
    icon: '🐙',
    defaultData: {
      label: 'GitHub',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'twitter_source',
    category: 'source',
    label: 'Twitter/X',
    description: 'Search tweets or user timeline',
    icon: '🐦',
    defaultData: {
      label: 'Twitter',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'youtube_source',
    category: 'source',
    label: 'YouTube',
    description: 'Channel videos or search results',
    icon: '📺',
    defaultData: {
      label: 'YouTube',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'producthunt_source',
    category: 'source',
    label: 'Product Hunt',
    description: 'Today\'s top products',
    icon: '🚀',
    defaultData: {
      label: 'Product Hunt',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'news_api_source',
    category: 'source',
    label: 'News API',
    description: 'Global news from 50,000+ sources',
    icon: '📰',
    defaultData: {
      label: 'News API',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'google_news_source',
    category: 'source',
    label: 'Google News',
    description: 'Search Google News',
    icon: '🔍',
    defaultData: {
      label: 'Google News',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'crypto_price_source',
    category: 'source',
    label: 'Crypto Prices',
    description: 'Track cryptocurrency prices',
    icon: '₿',
    defaultData: {
      label: 'Crypto Prices',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'stock_price_source',
    category: 'source',
    label: 'Stock Prices',
    description: 'Track stock market prices',
    icon: '📈',
    defaultData: {
      label: 'Stock Prices',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'weather_source',
    category: 'source',
    label: 'Weather',
    description: 'Weather forecasts and alerts',
    icon: '🌤️',
    defaultData: {
      label: 'Weather',
      category: 'source',
      configured: false,
      maxItems: 5,
    },
  },
  {
    type: 'gmail_source',
    category: 'source',
    label: 'Gmail',
    description: 'Fetch emails from Gmail',
    icon: '✉️',
    defaultData: {
      label: 'Gmail',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'podcast_source',
    category: 'source',
    label: 'Podcast Feed',
    description: 'Episodes from podcast RSS',
    icon: '🎙️',
    defaultData: {
      label: 'Podcast',
      category: 'source',
      configured: false,
      maxItems: 10,
    },
  },

  // ========== FILTER NODES ==========
  {
    type: 'dedupe_filter',
    category: 'filter',
    label: 'Deduplicate',
    description: 'Remove duplicate items by field',
    icon: '🔍',
    defaultData: {
      label: 'Dedupe',
      category: 'filter',
      configured: false,
      field: 'title',
    },
  },
  {
    type: 'date_filter',
    category: 'filter',
    label: 'Date Filter',
    description: 'Filter items by publication date',
    icon: '📅',
    defaultData: {
      label: 'Date Filter',
      category: 'filter',
      configured: false,
    },
  },
  {
    type: 'keyword_filter',
    category: 'filter',
    label: 'Keyword Filter',
    description: 'Filter items by keywords',
    icon: '🔑',
    defaultData: {
      label: 'Keyword Filter',
      category: 'filter',
      configured: false,
      keywords: [],
      mode: 'include',
      field: 'title',
    },
  },
  {
    type: 'limit_filter',
    category: 'filter',
    label: 'Limit Items',
    description: 'Limit number of items',
    icon: '🔢',
    defaultData: {
      label: 'Limit',
      category: 'filter',
      configured: false,
      maxItems: 10,
    },
  },
  {
    type: 'sentiment_filter',
    category: 'filter',
    label: 'Sentiment Filter',
    description: 'Filter by positive/negative/neutral',
    icon: '😊',
    defaultData: {
      label: 'Sentiment Filter',
      category: 'filter',
      configured: false,
      sentiment: 'positive',
    },
  },
  {
    type: 'length_filter',
    category: 'filter',
    label: 'Length Filter',
    description: 'Filter by text length',
    icon: '📏',
    defaultData: {
      label: 'Length Filter',
      category: 'filter',
      configured: false,
      minLength: 0,
      maxLength: 10000,
    },
  },
  {
    type: 'score_filter',
    category: 'filter',
    label: 'Score Filter',
    description: 'Filter by minimum score',
    icon: '⭐',
    defaultData: {
      label: 'Score Filter',
      category: 'filter',
      configured: false,
      minScore: 0,
    },
  },
  {
    type: 'regex_filter',
    category: 'filter',
    label: 'Regex Filter',
    description: 'Filter by regex pattern',
    icon: '🔤',
    defaultData: {
      label: 'Regex Filter',
      category: 'filter',
      configured: false,
      pattern: '',
      field: 'content',
    },
  },
  {
    type: 'author_filter',
    category: 'filter',
    label: 'Author Filter',
    description: 'Filter by author or source',
    icon: '👤',
    defaultData: {
      label: 'Author Filter',
      category: 'filter',
      configured: false,
      authors: [],
      mode: 'include',
    },
  },
  {
    type: 'language_filter',
    category: 'filter',
    label: 'Language Filter',
    description: 'Filter by content language',
    icon: '🌍',
    defaultData: {
      label: 'Language Filter',
      category: 'filter',
      configured: false,
      languages: ['en'],
    },
  },
  {
    type: 'top_n_filter',
    category: 'filter',
    label: 'Top N',
    description: 'Select top N by metric',
    icon: '🏆',
    defaultData: {
      label: 'Top N',
      category: 'filter',
      configured: false,
      limit: 10,
    },
  },
  {
    type: 'random_sample_filter',
    category: 'filter',
    label: 'Random Sample',
    description: 'Random selection of items',
    icon: '🎲',
    defaultData: {
      label: 'Random Sample',
      category: 'filter',
      configured: false,
      limit: 10,
    },
  },
  {
    type: 'has_media_filter',
    category: 'filter',
    label: 'Has Media',
    description: 'Filter items with media',
    icon: '🖼️',
    defaultData: {
      label: 'Has Media',
      category: 'filter',
      configured: true,
      hasMedia: true,
    },
  },

  // ========== TRANSFORM NODES ==========
  {
    type: 'llm_summarize',
    category: 'transform',
    label: 'AI Summarize',
    description: 'Generate summaries using AI',
    icon: '✨',
    defaultData: {
      label: 'AI Summarize',
      category: 'transform',
      configured: false,
    },
  },
  {
    type: 'llm_extract',
    category: 'transform',
    label: 'AI Extract',
    description: 'Extract structured data using AI',
    icon: '🎯',
    defaultData: {
      label: 'AI Extract',
      category: 'transform',
      configured: false,
      fields: [],
    },
  },
  {
    type: 'llm_qa',
    category: 'transform',
    label: 'AI Q&A',
    description: 'Generate questions and answers',
    icon: '❓',
    defaultData: {
      label: 'AI Q&A',
      category: 'transform',
      configured: false,
      instruction: 'Generate question-answer pairs',
    },
  },
  {
    type: 'llm_custom',
    category: 'transform',
    label: 'AI Custom',
    description: 'Custom AI transformation',
    icon: '🤖',
    defaultData: {
      label: 'AI Custom',
      category: 'transform',
      configured: false,
      systemPrompt: '',
      userPrompt: '',
    },
  },
  {
    type: 'claude_agent',
    category: 'transform',
    label: 'Claude Agent',
    description: 'Runtime AI agent processing',
    icon: '🤖',
    defaultData: {
      label: 'Claude Agent',
      category: 'transform',
      configured: false,
      systemPrompt: '',
      userPromptTemplate: '',
    },
  },
  {
    type: 'sentiment_analysis',
    category: 'transform',
    label: 'Sentiment Analysis',
    description: 'Analyze sentiment (0-1 score)',
    icon: '😊',
    defaultData: {
      label: 'Sentiment Analysis',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'entity_extraction',
    category: 'transform',
    label: 'Entity Extraction',
    description: 'Extract people, places, orgs',
    icon: '🏷️',
    defaultData: {
      label: 'Entity Extraction',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'category_classification',
    category: 'transform',
    label: 'Category Classification',
    description: 'Auto-categorize content',
    icon: '📂',
    defaultData: {
      label: 'Categorize',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'translation',
    category: 'transform',
    label: 'Translation',
    description: 'Translate to other languages',
    icon: '🌍',
    defaultData: {
      label: 'Translation',
      category: 'transform',
      configured: false,
      targetLanguage: 'en',
    },
  },
  {
    type: 'text_cleanup',
    category: 'transform',
    label: 'Text Cleanup',
    description: 'Remove HTML, normalize text',
    icon: '🧹',
    defaultData: {
      label: 'Text Cleanup',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'url_extraction',
    category: 'transform',
    label: 'URL Extraction',
    description: 'Extract and expand URLs',
    icon: '🔗',
    defaultData: {
      label: 'URL Extraction',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'scoring_rank',
    category: 'transform',
    label: 'Scoring/Rank',
    description: 'Score items by criteria',
    icon: '📊',
    defaultData: {
      label: 'Scoring',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'field_mapping',
    category: 'transform',
    label: 'Field Mapping',
    description: 'Rename/restructure fields',
    icon: '🔀',
    defaultData: {
      label: 'Field Mapping',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'merge_items',
    category: 'transform',
    label: 'Merge Items',
    description: 'Combine multiple items',
    icon: '🔗',
    defaultData: {
      label: 'Merge Items',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'enrich_data',
    category: 'transform',
    label: 'Enrich Data',
    description: 'Add data from external APIs',
    icon: '⚡',
    defaultData: {
      label: 'Enrich Data',
      category: 'transform',
      configured: true,
    },
  },
  {
    type: 'kg_extract',
    category: 'transform',
    label: 'Extract to Knowledge Graph',
    description: 'Extract entities and store in Neo4j',
    icon: '🧠',
    defaultData: {
      label: 'KG Extract',
      category: 'transform',
      configured: false,
      entityTypes: ['person', 'organization', 'location', 'concept'],
      extractRelationships: true,
      minConfidence: 0.6,
    },
  },
  {
    type: 'kg_query',
    category: 'transform',
    label: 'Query Knowledge Graph',
    description: 'Enrich items with graph data',
    icon: '🔍',
    defaultData: {
      label: 'KG Query',
      category: 'transform',
      configured: false,
      queryType: 'entity_lookup',
      enrichItems: true,
    },
  },

  // ========== OUTPUT NODES ==========
  {
    type: 'sms_output',
    category: 'output',
    label: 'SMS Output',
    description: 'Send results via SMS',
    icon: '💬',
    defaultData: {
      label: 'SMS',
      category: 'output',
      configured: false,
      template: '{{summary}}',
      maxLength: 1600,
    },
  },
  {
    type: 'report_output',
    category: 'output',
    label: 'Report Output',
    description: 'Generate markdown report',
    icon: '📄',
    defaultData: {
      label: 'Report',
      category: 'output',
      configured: false,
      template: '# {{title}}\n\n{{summary}}',
      includeRaw: false,
    },
  },
  {
    type: 'email_output',
    category: 'output',
    label: 'Email',
    description: 'Send via email',
    icon: '✉️',
    defaultData: {
      label: 'Email',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'webhook_output',
    category: 'output',
    label: 'Webhook',
    description: 'POST to HTTP endpoint',
    icon: '🔗',
    defaultData: {
      label: 'Webhook',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'slack_output',
    category: 'output',
    label: 'Slack',
    description: 'Post to Slack channel',
    icon: '💬',
    defaultData: {
      label: 'Slack',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'discord_output',
    category: 'output',
    label: 'Discord',
    description: 'Post to Discord channel',
    icon: '🎮',
    defaultData: {
      label: 'Discord',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'twitter_output',
    category: 'output',
    label: 'Twitter/X',
    description: 'Post tweet to Twitter',
    icon: '🐦',
    defaultData: {
      label: 'Twitter',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'notification_output',
    category: 'output',
    label: 'Push Notification',
    description: 'Send push notification',
    icon: '🔔',
    defaultData: {
      label: 'Notification',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'database_output',
    category: 'output',
    label: 'Database',
    description: 'Insert into SQL database',
    icon: '🗄️',
    defaultData: {
      label: 'Database',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'sheets_output',
    category: 'output',
    label: 'Google Sheets',
    description: 'Append to spreadsheet',
    icon: '📊',
    defaultData: {
      label: 'Sheets',
      category: 'output',
      configured: false,
    },
  },
  {
    type: 'file_export_output',
    category: 'output',
    label: 'File Export',
    description: 'Export as CSV/JSON',
    icon: '📁',
    defaultData: {
      label: 'File Export',
      category: 'output',
      configured: false,
    },
  },
];

/**
 * Get palette items by category
 */
export function getNodesByCategory(category: string) {
  return NODE_PALETTE.filter((item) => item.category === category);
}

/**
 * Get palette item by type
 */
export function getNodePaletteItem(type: string) {
  return NODE_PALETTE.find((item) => item.type === type);
}

/**
 * Node categories for UI grouping
 */
export const NODE_CATEGORIES = [
  { id: 'source', label: 'Sources', color: 'bg-blue-500' },
  { id: 'filter', label: 'Filters', color: 'bg-purple-500' },
  { id: 'transform', label: 'Transforms', color: 'bg-green-500' },
  { id: 'output', label: 'Outputs', color: 'bg-orange-500' },
];
