# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

# Resolve React Native root directory
react_native_path = '../ReactNativeWidgets'

target 'Webtoys' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # React Native pods
  pod 'FBLazyVector', :path => "#{react_native_path}/node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{react_native_path}/node_modules/react-native/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{react_native_path}/node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{react_native_path}/node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => "#{react_native_path}/node_modules/react-native/"
  pod 'React-Core', :path => "#{react_native_path}/node_modules/react-native/"
  pod 'React-CoreModules', :path => "#{react_native_path}/node_modules/react-native/React/CoreModules"
  pod 'React-Core/DevSupport', :path => "#{react_native_path}/node_modules/react-native/"
  pod 'React-RCTActionSheet', :path => "#{react_native_path}/node_modules/react-native/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{react_native_path}/node_modules/react-native/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{react_native_path}/node_modules/react-native/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{react_native_path}/node_modules/react-native/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{react_native_path}/node_modules/react-native/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{react_native_path}/node_modules/react-native/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{react_native_path}/node_modules/react-native/Libraries/Settings"
  pod 'React-RCTText', :path => "#{react_native_path}/node_modules/react-native/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{react_native_path}/node_modules/react-native/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{react_native_path}/node_modules/react-native/"

  pod 'React-cxxreact', :path => "#{react_native_path}/node_modules/react-native/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{react_native_path}/node_modules/react-native/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{react_native_path}/node_modules/react-native/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{react_native_path}/node_modules/react-native/ReactCommon/jsinspector"
  pod 'ReactCommon/callinvoker', :path => "#{react_native_path}/node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{react_native_path}/node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => "#{react_native_path}/node_modules/react-native/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => "#{react_native_path}/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{react_native_path}/node_modules/react-native/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{react_native_path}/node_modules/react-native/third-party-podspecs/Folly.podspec"

  # Additional React Native dependencies
  pod 'RNCAsyncStorage', :path => "#{react_native_path}/node_modules/@react-native-async-storage/async-storage"

  post_install do |installer|
    react_native_post_install(installer)
    
    # Silence deployment target warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end