#!/usr/bin/env node
/**
 * Jambot inventory — systematically exercises every instrument, effect, and
 * service through the headless tool layer (the same surface the agent uses),
 * renders WAVs, and measures them. Prints a markdown table + writes JSON.
 *
 *   node jambot/tests/inventory.js [outDir]
 *
 * Pass criteria are deliberately observable (signal present, pitch correct,
 * effect changes the audio in the expected direction) — not "didn't throw".
 * Results feed jambot/INVENTORY.md.
 */
import { JambotHeadless } from '../headless.js';
import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const OUT = process.argv[2] || join(process.cwd(), 'inventory-out');
mkdirSync(OUT, { recursive: true });
const BPM = 128;
const results = [];
const rec = (group, name, ok, detail = '') => { results.push({ group, name, ok, detail }); console.log(`${ok ? 'PASS' : 'FAIL'}  [${group}] ${name} — ${detail}`); };

// ---------- WAV analysis (no deps) ----------
function readWav(path) {
  const b = readFileSync(path); let p = 12, fmt = null, off = 0, len = 0;
  while (p < b.length) { const id = b.toString('ascii', p, p + 4), n = b.readUInt32LE(p + 4);
    if (id === 'fmt ') fmt = { tag: b.readUInt16LE(p + 8), ch: b.readUInt16LE(p + 10), sr: b.readUInt32LE(p + 12), bits: b.readUInt16LE(p + 22) };
    if (id === 'data') { off = p + 8; len = n; break; } p += 8 + n + (n & 1); }
  const { tag, ch, sr, bits } = fmt; const bps = bits / 8; const frames = Math.floor(len / (bps * ch));
  const chans = Array.from({ length: ch }, () => new Float32Array(frames));
  for (let i = 0; i < frames; i++) for (let c = 0; c < ch; c++) { const o = off + (i * ch + c) * bps;
    chans[c][i] = tag === 3 ? b.readFloatLE(o) : bits === 16 ? b.readInt16LE(o) / 32768 : bits === 24 ? ((b[o] | (b[o+1] << 8) | (b[o+2] << 16)) << 8 >> 8) / 8388608 : b.readInt32LE(o) / 2147483648; }
  return { sr, ch, frames, chans, dur: frames / sr };
}
const mono = (w) => { const m = new Float32Array(w.frames); for (let i = 0; i < w.frames; i++) { let s = 0; for (const c of w.chans) s += c[i]; m[i] = s / w.ch; } return m; };
const dB = (v) => 20 * Math.log10(v + 1e-12);
function stats(w) { const m = mono(w); let peak = 0, sq = 0, nan = 0, clip = 0; for (const c of w.chans) for (let i = 0; i < c.length; i++) { const v = c[i]; if (Number.isNaN(v)) { nan++; continue; } const a = Math.abs(v); if (a > peak) peak = a; if (a >= 0.999) clip++; } for (let i = 0; i < m.length; i++) sq += m[i] * m[i];
  return { peakDb: +dB(peak).toFixed(1), rmsDb: +dB(Math.sqrt(sq / m.length)).toFixed(1), nan, clip, dur: +w.dur.toFixed(3) }; }
function rmsWindow(x, sr, t0, t1) { const a = Math.max(0, Math.floor(t0 * sr)), b = Math.min(x.length, Math.floor(t1 * sr)); let s = 0; for (let i = a; i < b; i++) s += x[i] * x[i]; return Math.sqrt(s / Math.max(1, b - a)); }
// RBJ biquad
function biquad(type, f0, sr, Q = 0.707) { const w = 2 * Math.PI * f0 / sr, cs = Math.cos(w), sn = Math.sin(w), al = sn / (2 * Q); let b0, b1, b2, a0, a1, a2;
  if (type === 'lp') { b0 = (1 - cs) / 2; b1 = 1 - cs; b2 = (1 - cs) / 2; } else if (type === 'hp') { b0 = (1 + cs) / 2; b1 = -(1 + cs); b2 = (1 + cs) / 2; } else { b0 = al; b1 = 0; b2 = -al; }
  a0 = 1 + al; a1 = -2 * cs; a2 = 1 - al; return { b0: b0 / a0, b1: b1 / a0, b2: b2 / a0, a1: a1 / a0, a2: a2 / a0 }; }
function filt(x, c, passes = 2) { let y = x; for (let p = 0; p < passes; p++) { const o = new Float32Array(y.length); let x1 = 0, x2 = 0, y1 = 0, y2 = 0; for (let i = 0; i < y.length; i++) { const v = c.b0 * y[i] + c.b1 * x1 + c.b2 * x2 - c.a1 * y1 - c.a2 * y2; x2 = x1; x1 = y[i]; y2 = y1; y1 = v; o[i] = v; } y = o; } return y; }
const bandRms = (x, sr, lo, hi) => { let y = x; if (lo) y = filt(y, biquad('hp', lo, sr)); if (hi) y = filt(y, biquad('lp', hi, sr)); return rmsWindow(y, sr, 0, y.length / sr); };
function onsets(x, sr, { lo = 0, hi = 0, refractory = 0.08, thresh = 0.15 } = {}) { let y = x; if (lo) y = filt(y, biquad('hp', lo, sr)); if (hi) y = filt(y, biquad('lp', hi, sr));
  const hop = Math.round(sr / 200); const env = []; for (let i = 0; i + hop <= y.length; i += hop) { let s = 0; for (let j = i; j < i + hop; j++) s += y[j] * y[j]; env.push(Math.sqrt(s / hop)); }
  const mx = Math.max(...env); const out = []; let last = -1e9; for (let i = 1; i < env.length; i++) { const t = i * hop / sr; if (env[i] > thresh * mx && env[i] - env[i - 1] > 0.25 * env[i] && t - last > refractory) { out.push(+t.toFixed(3)); last = t; } } return out; }
function differ(a, b) { const x = mono(a), y = mono(b); const n = Math.min(x.length, y.length); let d = 0; for (let i = 0; i < n; i++) d += Math.abs(x[i] - y[i]); return d / n; }
const noteHz = (n) => { const m = n.match(/^([A-G])(#?)(-?\d)$/); const idx = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 }[m[1]] + (m[2] ? 1 : 0); return 440 * Math.pow(2, (idx + 12 * (parseInt(m[3]) + 1) - 69) / 12); };
// Goertzel-based fundamental check: energy at expected f0 (and octave neighbors) vs a flat comb of decoys
function goertzel(x, sr, f) { const k = 2 * Math.PI * f / sr, c = 2 * Math.cos(k); let s0 = 0, s1 = 0, s2 = 0; const n = Math.min(x.length, sr * 2); for (let i = 0; i < n; i++) { s0 = x[i] + c * s1 - s2; s2 = s1; s1 = s0; } return Math.sqrt(Math.max(0, s1 * s1 + s2 * s2 - c * s1 * s2)) / n; }
function pitchCheck(x, sr, note) { const f0 = noteHz(note); const cands = { 'f0': f0, 'oct-1': f0 / 2, 'oct+1': f0 * 2 }; const e = Object.fromEntries(Object.entries(cands).map(([k, f]) => [k, goertzel(x, sr, f)]));
  const decoy = [f0 * 1.19, f0 * 1.41, f0 * 1.68, f0 * 0.84].map(f => goertzel(x, sr, f)); const noise = Math.max(...decoy); const best = Object.entries(e).sort((a, b) => b[1] - a[1])[0];
  return { ok: e.f0 > 3 * noise || (best[1] > 3 * noise), best: best[0], f0Db: +dB(e.f0).toFixed(1), noiseDb: +dB(noise).toFixed(1) }; }

// ---------- helpers ----------
const fresh = () => new JambotHeadless({ bpm: BPM, outputDir: OUT });
const wavPath = (name) => join(OUT, `${name}.wav`);
async function render(jb, name, bars = 2) { const r = await jb.render(wavPath(name), bars); const p = wavPath(name); if (!existsSync(p)) throw new Error(`no WAV written (${String(r).slice(0, 120)})`); return { w: readWav(p), msg: String(r) }; }
const melodic = (note, steps = [0, 4, 8, 12], extra = {}) => Array.from({ length: 16 }, (_, i) => ({ note, gate: steps.includes(i), accent: i === 0, slide: false, velocity: 1, ...extra }));
const hasSignal = (s) => s.nan === 0 && s.peakDb > -30;
const fmt = (s) => `peak ${s.peakDb} dBFS, rms ${s.rmsDb}, clip ${s.clip}, ${s.dur}s`;
async function safe(group, name, fn) { try { await fn(); } catch (e) { rec(group, name, false, `threw: ${e.message.slice(0, 160)}`); } }

// ---------- instruments ----------
async function drumMachine(id, tool, voices, combo) {
  for (const v of voices) await safe(id, `voice ${v}`, async () => { const jb = fresh(); await jb.tool(tool, { clear: true, [v]: [0, 4, 8, 12] }); const { w } = await render(jb, `${id}-${v}`, 1); const s = stats(w); const on = onsets(mono(w), w.sr); rec(id, `voice ${v}`, hasSignal(s) && on.length >= 3, `${fmt(s)}, onsets ${on.length}/4 at ${on.slice(0, 4).join(',')}`); });
  await safe(id, 'full kit', async () => { const jb = fresh(); await jb.tool(tool, { clear: true, ...combo }); const { w } = await render(jb, `${id}-kit`, 2); const s = stats(w); rec(id, 'full kit (2 bars)', hasSignal(s) && s.clip === 0 && Math.abs(s.dur - (3.75 + 2)) < 0.05, `${fmt(s)} (2 bars + 2 s tail)`); });
}
await drumMachine('jb01', 'add_jb01', ['kick', 'snare', 'clap', 'ch', 'oh', 'lowtom', 'hitom', 'cymbal'], { kick: [0, 4, 8, 12], snare: [4, 12], clap: [4, 12], ch: [0, 2, 4, 6, 8, 10, 12, 14], oh: [2, 6, 10, 14], lowtom: [7], hitom: [15], cymbal: [0] });
await drumMachine('jt90', 'add_jt90', ['kick', 'snare', 'clap', 'rimshot', 'lowtom', 'midtom', 'hitom', 'ch', 'oh', 'crash', 'ride'], { kick: [0, 4, 8, 12], snare: [4, 12], clap: [4, 12], rimshot: [3, 11], lowtom: [7], midtom: [9], hitom: [15], ch: [0, 2, 4, 6, 8, 10, 12, 14], oh: [2, 6, 10, 14], crash: [0], ride: [1, 5, 9, 13] });

async function synth(id, addTool, tweakTool, note, tweaks) {
  await safe(id, 'pattern renders + pitch', async () => { const jb = fresh(); await jb.tool(addTool, { pattern: melodic(note) }); const { w } = await render(jb, `${id}-${note}`, 1); const s = stats(w); const pc = pitchCheck(mono(w), w.sr, note); rec(id, `pattern renders + pitch (${note})`, hasSignal(s) && pc.ok, `${fmt(s)}; f0 ${pc.f0Db} dB vs decoys ${pc.noiseDb} dB, strongest: ${pc.best}`); });
  await safe(id, 'accent + slide', async () => { const jb = fresh(); const pat = melodic(note, [0, 2, 4, 6, 8, 10, 12, 14]).map((s, i) => ({ ...s, accent: i % 4 === 0, slide: i % 4 === 2 })); await jb.tool(addTool, { pattern: pat }); const { w } = await render(jb, `${id}-accent-slide`, 1); const s = stats(w); rec(id, 'accent + slide pattern', hasSignal(s), fmt(s)); });
  if (tweakTool && tweaks) await safe(id, 'filter tweak audible', async () => { const a = fresh(); await a.tool(addTool, { pattern: melodic(note) }); await a.tool(tweakTool, tweaks.dark); const wa = (await render(a, `${id}-dark`, 1)).w; const b = fresh(); await b.tool(addTool, { pattern: melodic(note) }); await b.tool(tweakTool, tweaks.bright); const wb = (await render(b, `${id}-bright`, 1)).w;
    const ha = bandRms(mono(wa), wa.sr, 2000, 0), hb = bandRms(mono(wb), wb.sr, 2000, 0); const diff = dB(hb) - dB(ha); rec(id, 'filter tweak audible (bright vs dark >2kHz)', diff > 6, `high-band +${diff.toFixed(1)} dB brighter with cutoff ${tweaks.bright.filterCutoff} vs ${tweaks.dark.filterCutoff}`); });
}
await synth('jb202', 'add_jb202', 'tweak_jb202', 'C2', { dark: { filterCutoff: 200 }, bright: { filterCutoff: 6000 } });
await synth('jt30', 'add_jt30', 'tweak_jt30', 'C2', { dark: { filterCutoff: 200, filterEnvAmount: 0 }, bright: { filterCutoff: 6000, filterEnvAmount: 0 } });
await synth('jt10', 'add_jt10', 'tweak_jt10', 'C3', { dark: { filterCutoff: 200 }, bright: { filterCutoff: 8000 } });

// JP9000 presets + a custom module patch
for (const preset of ['basic', 'pluck', 'dualBass']) await safe('jp9000', `preset ${preset}`, async () => { const jb = fresh(); const m = await jb.tool('add_jp9000', { preset }); await jb.tool('add_jp9000_pattern', { pattern: melodic('C3') }); let { w } = await render(jb, `jp9000-${preset}`, 1); let s = stats(w); let note = '';
  if (!hasSignal(s)) { const show = String(await jb.tool('show_jp9000', {})); note = ` | silent; show_jp9000: ${show.replace(/\s+/g, ' ').slice(0, 200)}`; }
  const pc = hasSignal(s) ? pitchCheck(mono(w), w.sr, 'C3') : { ok: false, best: '-', f0Db: 0, noiseDb: 0 }; rec('jp9000', `preset ${preset}`, hasSignal(s), `${fmt(s)}; pitch C3 ${pc.ok ? 'ok' : 'unclear'} (strongest ${pc.best})${note}`); });
await safe('jp9000', 'custom patch (pluck + env→filter)', async () => { const jb = fresh(); await jb.tool('add_jp9000', { preset: 'pluck' }); const r1 = await jb.tool('add_module', { type: 'env-adsr', id: 'env1' }); const r2 = await jb.tool('connect_modules', { from: 'env1.cv', to: 'filter1.cutoffCV' }); await jb.tool('tweak_module', { module: 'filter1', param: 'envAmount', value: 50 }); await jb.tool('add_jp9000_pattern', { pattern: melodic('C3') }); const { w } = await render(jb, 'jp9000-custom', 1); const s = stats(w); rec('jp9000', 'custom patch (add_module/connect_modules)', hasSignal(s) && !/error/i.test(r1 + r2), `${fmt(s)}; ${String(r1).slice(0, 60)} / ${String(r2).slice(0, 60)}`); });

// JB-S sampler
await safe('jbs', 'kits', async () => { const jb = fresh(); const kits = String(await jb.tool('list_jbs_kits', {})); rec('jbs', 'list_jbs_kits', /808/.test(kits) && /amber/.test(kits), kits.replace(/\s+/g, ' ').slice(0, 140)); });
for (const kit of ['808', 'amber']) { for (const slot of ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10']) await safe('jbs', `${kit} ${slot}`, async () => { const jb = fresh(); await jb.tool('load_jbs_kit', { kit }); await jb.tool('add_jbs', { [slot]: [0, 4, 8, 12] }); const { w } = await render(jb, `jbs-${kit}-${slot}`, 1); const s = stats(w); rec('jbs', `kit ${kit} slot ${slot}`, hasSignal(s), fmt(s)); }); }
await safe('jbs', 'velocity', async () => { const jb = fresh(); await jb.tool('load_jbs_kit', { kit: '808' }); await jb.tool('add_jbs', { s1: [{ step: 0, vel: 1 }, { step: 8, vel: 0.25 }] }); const { w } = await render(jb, 'jbs-vel', 1); const x = mono(w); const a = rmsWindow(x, w.sr, 0, 0.2), b = rmsWindow(x, w.sr, 0.9375, 1.1375); rec('jbs', 'per-hit velocity', dB(a) - dB(b) > 6, `vel 1.0 hit ${dB(a).toFixed(1)} dB vs vel 0.25 hit ${dB(b).toFixed(1)} dB`); });

// JB200 (deprecated alias) smoke
await safe('jb200', 'deprecated alias renders', async () => { const jb = fresh(); const m = String(await jb.tool('add_jb200', { pattern: melodic('C2') })); const { w } = await render(jb, 'jb200', 1); const s = stats(w); rec('jb200', 'deprecated alias (expected: no audio)', true, `${hasSignal(s) ? 'STILL RENDERS AUDIO' : 'renders silence — deprecated, do not use'}; ${fmt(s)}; ${m.slice(0, 60)}`); });

// ---------- effects ----------
async function singleNote(target = 'jt10') { const jb = fresh(); await jb.tool('add_jt10', { pattern: melodic('C3', [0]) }); return jb; }
await safe('delay', 'analog', async () => { const d = await singleNote(); const wd = (await render(d, 'delay-dry', 1)).w; const e = await singleNote(); const r = String(await e.tool('add_effect', { target: 'jt10', effect: 'delay', mode: 'analog', time: 375, sync: 'off', feedback: 60, mix: 60 })); const we = (await render(e, 'delay-analog', 1)).w;
  const xd = mono(wd), xe = mono(we); const echo = dB(rmsWindow(xe, we.sr, 0.38, 0.55)) - dB(rmsWindow(xd, wd.sr, 0.38, 0.55)); const echo2 = dB(rmsWindow(xe, we.sr, 0.76, 0.93)) - dB(rmsWindow(xd, wd.sr, 0.76, 0.93)); rec('delay', 'analog: echoes at 375/750 ms', echo > 6 && echo2 > 6 && differ(wd, we) > 1e-4, `echo1 +${echo.toFixed(1)} dB, echo2 +${echo2.toFixed(1)} dB over dry; ${r.slice(0, 60)}`); });
await safe('delay', 'pingpong', async () => { const e = await singleNote(); await e.tool('add_effect', { target: 'jt10', effect: 'delay', mode: 'pingpong', time: 250, sync: 'off', feedback: 60, mix: 60, spread: 100 }); const we = (await render(e, 'delay-pingpong', 1)).w; if (we.ch < 2) return rec('delay', 'pingpong: stereo bounce', false, 'render is mono'); const L = we.chans[0], R = we.chans[1]; const n = L.length; let sd = 0, ss = 0; for (let i = 0; i < n; i++) { sd += (L[i] - R[i]) ** 2; ss += (L[i] + R[i]) ** 2; } const width = Math.sqrt(sd / ss); const lr = [[0.24, 0.30], [0.49, 0.55]].map(([a, b]) => (dB(rmsWindow(L, we.sr, a, b)) - dB(rmsWindow(R, we.sr, a, b))).toFixed(1)); rec('delay', 'pingpong: stereo bounce', width > 0.2, `side/mid ${width.toFixed(2)}; L−R at echo1 ${lr[0]} dB, echo2 ${lr[1]} dB`); });
await safe('delay', 'tempo sync', async () => { const e = await singleNote(); await e.tool('add_effect', { target: 'jt10', effect: 'delay', mode: 'analog', sync: '8th', feedback: 50, mix: 60 }); const we = (await render(e, 'delay-sync', 1)).w; const x = mono(we); const t8 = 60 / BPM / 2; const on = dB(rmsWindow(x, we.sr, t8 + 0.01, t8 + 0.10)), off = dB(rmsWindow(x, we.sr, t8 - 0.12, t8 - 0.02)); rec('delay', 'tempo sync (8th = 234 ms)', on - off > 6, `energy at 8th-note echo +${(on - off).toFixed(1)} dB vs just before`); });
await safe('delay', 'on jb01 voice', async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0] }); const wd = (await render(jb, 'delay-voice-dry', 1)).w; const e = fresh(); await e.tool('add_jb01', { clear: true, ch: [0] }); await e.tool('add_effect', { target: 'jb01.ch', effect: 'delay', mode: 'analog', time: 300, sync: 'off', feedback: 50, mix: 60 }); const we = (await render(e, 'delay-voice', 1)).w; const g = dB(rmsWindow(mono(we), we.sr, 0.30, 0.40)) - dB(rmsWindow(mono(wd), wd.sr, 0.30, 0.40)); rec('delay', 'per-voice target (jb01.ch)', g > 6, `echo +${g.toFixed(1)} dB over dry at 300 ms`); });
for (const target of ['jt10', 'jb01', 'master']) await safe('reverb', target, async () => { const mk = async () => { const jb = fresh(); if (target === 'jt10') await jb.tool('add_jt10', { pattern: melodic('C3', [0]) }); else await jb.tool('add_jb01', { clear: true, snare: [0] }); return jb; }; const d = await mk(); const wd = (await render(d, `reverb-${target}-dry`, 1)).w; const e = await mk(); const r = String(await e.tool('add_effect', { target, effect: 'reverb', decay: 3, size: 70, mix: 60 })); const we = (await render(e, `reverb-${target}`, 1)).w; const tail = dB(rmsWindow(mono(we), we.sr, 0.5, 1.2)) - dB(rmsWindow(mono(wd), wd.sr, 0.5, 1.2)); const diff = differ(wd, we); rec('reverb', `target ${target}: tail + wet≠dry`, tail > 6 && diff > 1e-4, `tail +${tail.toFixed(1)} dB over dry (0.5–1.2 s), mean |wet−dry| ${diff.toExponential(1)}; ${r.slice(0, 50)}`); });
await safe('eq', 'channel insert', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, kick: [0, 4, 8, 12], ch: [0, 2, 4, 6, 8, 10, 12, 14] }); return jb; }; const d = await mk(); const wd = (await render(d, 'eq-dry', 1)).w; const e = await mk(); const r = String(await e.tool('add_channel_insert', { channel: 'jb01', effect: 'eq', params: { highGain: -18 } })); const we = (await render(e, 'eq-highcut', 1)).w; const hi = dB(bandRms(mono(we), we.sr, 4000, 0)) - dB(bandRms(mono(wd), wd.sr, 4000, 0)); const lo = dB(bandRms(mono(we), we.sr, 0, 150)) - dB(bandRms(mono(wd), wd.sr, 0, 150)); rec('eq', 'channel insert jb01 highGain −18', hi < -6 && Math.abs(lo) < 3, `>4 kHz ${hi.toFixed(1)} dB, <150 Hz ${lo.toFixed(1)} dB; ${r.slice(0, 60)}`); });
await safe('eq', 'master insert', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, kick: [0, 4, 8, 12], ch: [0, 2, 4, 6, 8, 10, 12, 14] }); return jb; }; const d = await mk(); const wd = (await render(d, 'eqm-dry', 1)).w; const e = await mk(); const r = String(await e.tool('add_master_insert', { effect: 'eq', params: { lowGain: -18 } })); const we = (await render(e, 'eqm-lowcut', 1)).w; const lo = dB(bandRms(mono(we), we.sr, 0, 120)) - dB(bandRms(mono(wd), wd.sr, 0, 120)); const hi = dB(bandRms(mono(we), we.sr, 4000, 0)) - dB(bandRms(mono(wd), wd.sr, 4000, 0)); rec('eq', 'master insert lowGain −18', lo < -6 && Math.abs(hi) < 3, `<120 Hz ${lo.toFixed(1)} dB, >4 kHz ${hi.toFixed(1)} dB; ${r.slice(0, 60)}`); });
await safe('filter', 'per-voice lowpass', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0, 2, 4, 6, 8, 10, 12, 14] }); return jb; }; const d = await mk(); const wd = (await render(d, 'filter-dry', 1)).w; const e = await mk(); const r = String(await e.tool('add_channel_insert', { channel: 'ch', effect: 'filter', params: { mode: 'lowpass', cutoff: 400, resonance: 10 } })); const we = (await render(e, 'filter-lp', 1)).w; const hi = dB(bandRms(mono(we), we.sr, 3000, 0)) - dB(bandRms(mono(wd), wd.sr, 3000, 0)); rec('filter', 'per-voice lowpass 400 Hz on ch', hi < -12, `>3 kHz ${hi.toFixed(1)} dB vs dry; ${r.slice(0, 60)}`); });
await safe('filter', 'preset', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0, 2, 4, 6, 8, 10, 12, 14], kick: [0, 8] }); return jb; }; const d = await mk(); const wd = (await render(d, 'filter-tel-dry', 1)).w; const e = await mk(); const r = String(await e.tool('add_channel_insert', { channel: 'jb01', effect: 'filter', preset: 'telephone' })); const we = (await render(e, 'filter-telephone', 1)).w; const lo = dB(bandRms(mono(we), we.sr, 0, 120)) - dB(bandRms(mono(wd), wd.sr, 0, 120)), hi = dB(bandRms(mono(we), we.sr, 3000, 0)) - dB(bandRms(mono(wd), wd.sr, 3000, 0)), mid = dB(bandRms(mono(we), we.sr, 800, 2500)) - dB(bandRms(mono(wd), wd.sr, 800, 2500)); rec('filter', "preset 'telephone' (bandpass 1.5 kHz) on jb01", lo < -12 && hi < -6 && mid > lo + 6, `vs dry: <120 Hz ${lo.toFixed(1)} dB, 800–2.5k ${mid.toFixed(1)} dB, >3 kHz ${hi.toFixed(1)} dB; ${r.slice(0, 40)}`); });
await safe('jp9000', 'level headroom', async () => { const jb = fresh(); await jb.tool('add_jp9000', { preset: 'basic' }); await jb.tool('tweak', { path: 'jp9000.level', value: -14 }); await jb.tool('add_jp9000_pattern', { pattern: melodic('C3') }); const { w } = await render(jb, 'jp9000-basic-minus9', 1); const s = stats(w); rec('jp9000', 'preset basic with jp9000.level −14 dB (clip workaround)', hasSignal(s) && s.clip === 0, fmt(s)); });
await safe('filter', 'whole-channel lowpass + param readback', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0, 2, 4, 6, 8, 10, 12, 14], kick: [0, 8] }); return jb; }; const d = await mk(); const wd = (await render(d, 'filter-ch-dry', 1)).w; const e = await mk(); await e.tool('add_channel_insert', { channel: 'jb01', effect: 'filter', params: { mode: 'lowpass', cutoff: 400, resonance: 10 } }); const g = String(await e.tool('get_param', { path: 'fx.jb01.filter1.cutoff' })); const we = (await render(e, 'filter-ch-lp', 1)).w; const hi = dB(bandRms(mono(we), we.sr, 3000, 0)) - dB(bandRms(mono(wd), wd.sr, 3000, 0)); rec('filter', 'whole-channel lowpass 400 Hz on jb01', hi < -12, `>3 kHz ${hi.toFixed(1)} dB vs dry; readback ${g.trim()}`); });
await safe('filter', 'highpass mode', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0, 2, 4, 6, 8, 10, 12, 14], kick: [0, 8] }); return jb; }; const d = await mk(); const wd = (await render(d, 'filter-hp-dry', 1)).w; const e = await mk(); await e.tool('add_channel_insert', { channel: 'jb01', effect: 'filter', params: { mode: 'highpass', cutoff: 2000, resonance: 10 } }); const we = (await render(e, 'filter-hp', 1)).w; const lo = dB(bandRms(mono(we), we.sr, 0, 120)) - dB(bandRms(mono(wd), wd.sr, 0, 120)); rec('filter', 'whole-channel highpass 2 kHz on jb01', lo < -24, `<120 Hz ${lo.toFixed(1)} dB vs dry`); });
await safe('eq', 'per-voice insert', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0, 2, 4, 6, 8, 10, 12, 14] }); return jb; }; const d = await mk(); const wd = (await render(d, 'eqv-dry', 1)).w; const e = await mk(); const r = String(await e.tool('add_channel_insert', { channel: 'ch', effect: 'eq', params: { highGain: -18 } })); const we = (await render(e, 'eqv-ch', 1)).w; const hi = dB(bandRms(mono(we), we.sr, 4000, 0)) - dB(bandRms(mono(wd), wd.sr, 4000, 0)); rec('eq', 'per-voice insert (channel ch) highGain −18', hi < -6, `>4 kHz ${hi.toFixed(1)} dB vs dry (identical = insert ignored); ${r.slice(0, 50)}`); });
await safe('params', 'fx param readback', async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0, 4, 8, 12] }); await jb.tool('add_channel_insert', { channel: 'jb01', effect: 'filter', params: { mode: 'lowpass', cutoff: 400, resonance: 10 } }); await jb.tool('add_channel_insert', { channel: 'jb01', effect: 'eq', params: { highGain: -18 } }); const c = String(await jb.tool('get_param', { path: 'fx.jb01.filter1.cutoff' })).trim(), g = String(await jb.tool('get_param', { path: 'fx.jb01.eq1.highGain' })).trim(); rec('params', 'get_param on fx.* paths reads back what was set', /400/.test(c) && /-18/.test(g), `${c} | ${g}`); });
await safe('params', 'fx param write via tweak', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: [0, 2, 4, 6, 8, 10, 12, 14] }); await jb.tool('add_channel_insert', { channel: 'jb01', effect: 'filter', params: { mode: 'lowpass', cutoff: 12000, resonance: 10 } }); return jb; }; const a = await mk(); const wa = (await render(a, 'fxw-open', 1)).w; const b = await mk(); const r = String(await b.tool('tweak', { path: 'fx.jb01.filter1.cutoff', value: 300 })); const wb = (await render(b, 'fxw-closed', 1)).w; const hi = dB(bandRms(mono(wb), wb.sr, 3000, 0)) - dB(bandRms(mono(wa), wa.sr, 3000, 0)); rec('params', 'tweak fx.jb01.filter1.cutoff 12k→300 changes audio', hi < -12, `>3 kHz ${hi.toFixed(1)} dB after tweak; ${r.slice(0, 60)}`); });
await safe('sidechain', 'kick ducks jb202', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, kick: [0, 4, 8, 12] }); await jb.tool('add_jb202', { pattern: melodic('C2', Array.from({ length: 16 }, (_, i) => i), { slide: true }) }); return jb; }; const d = await mk(); const wd = (await render(d, 'sc-dry', 1)).w; const e = await mk(); const r = String(await e.tool('add_sidechain', { target: 'jb202', trigger: 'kick', amount: 0.9 })); const we = (await render(e, 'sc-wet', 1)).w;
  const beat = 60 / BPM; const ratio = (w) => { const x = filt(filt(mono(w), biquad('hp', 300, w.sr)), biquad('lp', 2000, w.sr)); let du = 0, re = 0; for (let k = 0; k < 4; k++) { du += rmsWindow(x, w.sr, k * beat + 0.02, k * beat + 0.12); re += rmsWindow(x, w.sr, k * beat + 0.30, k * beat + 0.44); } return dB(du / re); }; const rd = ratio(wd), rw = ratio(we); rec('sidechain', 'kick ducks jb202 (300–2k band, after-kick vs recovered)', rd - rw > 3 && differ(wd, we) > 1e-4, `dry ${rd.toFixed(1)} dB → wet ${rw.toFixed(1)} dB (${(rd - rw).toFixed(1)} dB more duck); ${r.slice(0, 50)}`); });

// ---------- services ----------
await safe('automation', 'ch decay sweep', async () => { const mk = async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, ch: Array.from({ length: 16 }, (_, i) => i) }); return jb; }; const d = await mk(); const wd = (await render(d, 'auto-dry', 1)).w; const e = await mk(); const r = String(await e.tool('automate', { path: 'jb01.ch.decay', values: [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 5, 5, 5, 5, 5, 5] })); const we = (await render(e, 'auto-ch', 1)).w; const x = mono(we); const first = dB(rmsWindow(x, we.sr, 0.03, 0.11)), last = dB(rmsWindow(x, we.sr, 1.78, 1.86)); rec('automation', 'automate jb01.ch.decay (long→short)', differ(wd, we) > 1e-4 && first - last > 6 && !/error/i.test(r), `step1 tail ${first.toFixed(1)} dB vs step16 tail ${last.toFixed(1)} dB; ${r.slice(0, 50)}`); });
await safe('song', 'arrangement', async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, kick: [0, 4, 8, 12] }); await jb.tool('save_pattern', { instrument: 'jb01', name: 'A' }); await jb.tool('add_jb01', { clear: true, kick: [0, 4, 8, 12], ch: [0, 2, 4, 6, 8, 10, 12, 14] }); await jb.tool('save_pattern', { instrument: 'jb01', name: 'B' }); const r = String(await jb.tool('set_arrangement', { sections: [{ bars: 2, jb01: 'A' }, { bars: 2, jb01: 'B' }] })); const { w } = await render(jb, 'song', 1); const s = stats(w); const x = mono(w); const hiA = dB(bandRms(x.slice(0, Math.floor(3.75 * w.sr)), w.sr, 4000, 0)), hiB = dB(bandRms(x.slice(Math.floor(3.75 * w.sr)), w.sr, 4000, 0)); rec('song', 'save_pattern + set_arrangement (A ×2, B ×2)', Math.abs(s.dur - (7.5 + 2)) < 0.05 && hiB - hiA > 6, `${s.dur}s (expect 7.5 + 2 s tail); hats only in B: +${(hiB - hiA).toFixed(1)} dB; ${r.slice(0, 50)}`); });
await safe('session', 'save/load', async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, kick: [0, 4, 8, 12], ch: [2, 6, 10, 14] }); await jb.tool('tweak', { path: 'jb01.kick.decay', value: 90 }); const w1 = (await render(jb, 'save-a', 1)).w; const state = jb.save(); const jb2 = fresh(); jb2.load(state); const w2 = (await render(jb2, 'save-b', 1)).w; rec('session', 'save() → load() reproduces render', differ(w1, w2) < 1e-6, `mean |a−b| ${differ(w1, w2).toExponential(1)}`); });
await safe('params', 'get/tweak roundtrip', async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, kick: [0] }); await jb.tool('tweak', { path: 'jb01.kick.decay', value: 33 }); const g = String(await jb.tool('get_param', { path: 'jb01.kick.decay' })); const lp = String(await jb.tool('list_params', { node: 'jb01' })); rec('params', 'tweak → get_param roundtrip, list_params', /33/.test(g) && lp.length > 200, `${g.replace(/\s+/g, ' ').slice(0, 60)}; list_params ${lp.split('\n').length} lines`); });
await safe('analysis', 'tools', async () => { const jb = fresh(); await jb.tool('add_jt10', { pattern: melodic('A2', Array.from({ length: 16 }, (_, i) => i)) }); await jb.tool('tweak_jt10', { filterCutoff: 12000, filterResonance: 0 }); const p = wavPath('analysis-a2'); await render(jb, 'analysis-a2', 1); const sox = String(await jb.tool('check_sox', {})); const peaks = String(await jb.tool('get_spectral_peaks', { filename: p, maxFreq: 2000 })); const wf = String(await jb.tool('detect_waveform', { filename: p })); const an = String(await jb.tool('analyze_render', { filename: p })); const peakOk = /A2|110Hz|\b11[0-1]Hz/.test(peaks); rec('analysis', 'check_sox', !/not (found|installed)/i.test(sox), sox.replace(/\s+/g, ' ').slice(0, 80)); rec('analysis', 'get_spectral_peaks finds A2 (110 Hz)', peakOk, peaks.split('\n').slice(0, 3).join(' | ').slice(0, 160)); rec('analysis', 'detect_waveform', /saw|square|triangle|sine/i.test(wf), wf.split('\n').slice(0, 3).join(' | ').slice(0, 140)); rec('analysis', 'analyze_render', /peak|rms|lufs|level/i.test(an) && !/error/i.test(an), an.split('\n').slice(0, 2).join(' | ').slice(0, 140)); });
await safe('routing', 'tracks/sends smoke', async () => { const jb = fresh(); await jb.tool('add_jb01', { clear: true, kick: [0, 4, 8, 12] }); const outs = []; for (const [t, i] of [['list_tracks', {}], ['show_routing', {}], ['list_sends', {}], ['show_mixer', {}], ['show', { instrument: 'jb01' }], ['get_state', { node: 'jb01' }]]) outs.push(`${t}: ${String(await jb.tool(t, i)).replace(/\s+/g, ' ').slice(0, 70)}`); rec('routing', 'list_tracks/show_routing/list_sends/show_mixer/show/get_state respond', outs.every(o => !/error|unknown tool/i.test(o)), outs.join(' || ').slice(0, 400)); });

// ---------- summary ----------
const groups = [...new Set(results.map(r => r.group))];
console.log('\n| Group | Pass | Fail |'); console.log('|---|---|---|');
for (const g of groups) { const rs = results.filter(r => r.group === g); console.log(`| ${g} | ${rs.filter(r => r.ok).length} | ${rs.filter(r => !r.ok).length} |`); }
writeFileSync(join(OUT, 'inventory-results.json'), JSON.stringify({ date: new Date().toISOString(), bpm: BPM, results }, null, 1));
console.log(`\n${results.filter(r => r.ok).length} passed, ${results.filter(r => !r.ok).length} failed → ${join(OUT, 'inventory-results.json')}`);
