/**
 * Type definitions for Weekend Stories
 * These types define the structure for the scenes, conversations, and metadata
 * for weekend stories generated by the GPT model.
 */

/**
 * Represents a single message in a conversation
 */
export interface WeekendStoryMessage {
  /** Discord username of the coach (e.g., kailey_sloan, venusmetrics) */
  coach: string;
  /** Content of the message */
  content: string;
  /** Timestamp within the scene (e.g., "8:12 PM") */
  timestamp: string;
}

/**
 * Represents the scene introduction
 */
export interface WeekendStoryIntro {
  /** Time of the scene (e.g., "8:12 PM") */
  time: string;
  /** Location of the scene (e.g., "Berlin") */
  location: string;
  /** Specific behavior or detail in the scene */
  behavior: string;
}

/**
 * Represents a single scene in the weekend story
 */
export interface WeekendStoryScene {
  /** Scene number (1-24) */
  number: number;
  /** Scene introduction */
  intro: WeekendStoryIntro;
  /** Array of messages in the conversation */
  conversation: WeekendStoryMessage[];
}

/**
 * Metadata for the weekend story
 */
export interface WeekendStoryMetadata {
  /** ISO timestamp when the story was generated */
  generated: string;
  /** Type of the story (e.g., "weekend2") */
  storyType: string;
  /** City where the story takes place */
  city: string;
  /** Goal location in the story */
  locationGoal: string;
  /** Key object in the story */
  object: string;
}

/**
 * Represents a complete weekend story
 */
export interface WeekendStory {
  /** Metadata about the story */
  metadata: WeekendStoryMetadata;
  /** Array of scenes in the story */
  scenes: WeekendStoryScene[];
} 